Repository masters2023-2nd-project-05/second-hand, pull requests merged in 2023-08, with the labels that each got.

#347 [#269] build test
  front-end/.env.production
  front-end/package.json
  front-end/src/api.ts
  front-end/src/assets/Icon.tsx
  front-end/src/components/chat/ChatRoom/ChatRoom.tsx
  front-end/src/components/chat/ChatRoom/index.ts
  front-end/src/components/chat/ChatRoomList/ChatListItem.tsx
  front-end/src/components/chat/ChatRoomList/ChatRoomList.tsx
  front-end/src/components/common/Alert/Alert.tsx
  front-end/src/components/common/Alert/constants.ts
  front-end/src/components/common/Alert/index.ts
  front-end/src/components/common/Alert/useAlert.tsx
  front-end/src/components/common/ImgBox/ImgBox.tsx
  front-end/src/components/common/NavBar/NavBar.tsx
  front-end/src/components/common/PopupSheet/PopupSheet.tsx
  front-end/src/components/common/PopupSheet/constants.ts
  front-end/src/components/common/TabBar/ChatTabBar.tsx
  front-end/src/components/common/Textarea/Textarea.tsx
  front-end/src/components/home/ItemDetail/Carousel.tsx
  front-end/src/components/layout/MobileLayout.tsx
  front-end/src/components/layout/PortalLayout.tsx
  front-end/src/components/login/Join.tsx
  front-end/src/components/login/OAuthCallback.tsx
  front-end/src/components/new/CategoryList.tsx
  front-end/src/components/new/New.tsx
  front-end/src/components/new/itemEditor/ImageEditor.tsx
  front-end/src/components/new/itemEditor/ItemEditor.tsx
  front-end/src/components/new/itemEditor/TitleEditor.tsx
  front-end/src/components/region/RegionSelector.tsx
  front-end/src/components/region/SearchRegions.tsx
  front-end/src/components/region/SettingRegionMap.tsx
  front-end/src/components/region/SettingRegionSelector.tsx
  front-end/src/hooks/useAPI.tsx
  front-end/src/hooks/useBackDismiss.tsx
  front-end/src/hooks/useGeoLocation.tsx
  front-end/src/hooks/useOutsideClick.tsx
  front-end/src/pages/ChatPage.tsx
  front-end/src/pages/Home.tsx
  front-end/src/pages/ItemDetail.tsx
  front-end/src/pages/Login.tsx
  front-end/src/pages/SalesHistory.tsx
  front-end/src/pages/WishList.tsx
  front-end/src/utils/debounce.ts
  front-end/src/utils/formatText.ts
Labels: FE, release

#342 FEAT: 채팅 알림 구현
  backend/src/main/java/com/team5/secondhand/BackendApplication.java
  backend/src/main/java/com/team5/secondhand/api/member/service/MemberService.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/controller/ChatController.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/domain/ChatBubble.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/service/ChatLogService.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/service/RedisMessagePublisher.java
  backend/src/main/java/com/team5/secondhand/chat/notification/controller/NotificationController.java
  backend/src/main/java/com/team5/secondhand/chat/notification/domain/SseEvent.java
  backend/src/main/java/com/team5/secondhand/chat/notification/domain/SseKey.java
  backend/src/main/java/com/team5/secondhand/chat/notification/dto/ChatNotification.java
  backend/src/main/java/com/team5/secondhand/chat/notification/repository/InmemoryNotificationRepository.java
  backend/src/main/java/com/team5/secondhand/chat/notification/repository/NotificationRepository.java
  backend/src/main/java/com/team5/secondhand/chat/notification/service/NotificationService.java
  backend/src/main/java/com/team5/secondhand/chat/notification/service/SendChatNotificationUsecase.java
  backend/src/main/java/com/team5/secondhand/global/event/ChatBubbleArrivedEvent.java
  backend/src/main/java/com/team5/secondhand/global/model/BaseEvent.java
  backend/src/main/java/com/team5/secondhand/global/model/BasedTimeEntity.java
  backend/src/main/java/com/team5/secondhand/global/model/UpdatedTimeEntity.java
  backend/src/main/resources/application.yml
Labels: BE, feature

#359 [#340] FEAT: 엔터 키를 누를 때 특정 함수를 실행하는 커스텀 훅 작성
  front-end/src/components/common/TabBar/ChatTabBar.tsx
  front-end/src/hooks/useEnterKeyPress.tsx
  front-end/src/pages/Login.tsx
Labels: feature, FE

#362 [#360] FIX: 임시로 Lazy loading 에러 수정
  backend/src/main/java/com/team5/secondhand/api/chatroom/domian/Chatroom.java
Labels: BE, debug

#369 FEAT: 웹소켓 connect
  backend/src/main/java/com/team5/secondhand/chat/bubble/domain/MessageType.java
  backend/src/main/java/com/team5/secondhand/chat/chatroom/handler/StompErrorHandler.java
  backend/src/main/java/com/team5/secondhand/chat/chatroom/handler/StompMessageProcessor.java
  backend/src/main/java/com/team5/secondhand/chat/config/WebSocketMessageBroker.java
  backend/src/main/java/com/team5/secondhand/chat/exception/ErrorType.java
  backend/src/main/java/com/team5/secondhand/global/jwt/service/JwtService.java
Labels: BE, feature

#270 [#230] 채팅 기능 구현
  front-end/package.json
  front-end/src/components/chat/ChatRoom/ChatRoom.tsx
  front-end/src/components/chat/ChatRoomList/ChatListItem.tsx
  front-end/src/components/chat/ChatRoomList/ChatRoomList.tsx
  front-end/src/components/common/Item/Item.tsx
  front-end/src/pages/ChatPage.tsx
  front-end/src/pages/ItemDetail.tsx
  front-end/src/routes/router.tsx
  front-end/src/utils/formatPrice.ts
  node_modules/.yarn-integrity
  yarn.lock
Labels: feature, FE

#370 [#346] TODO
  front-end/src/components/common/Alert/useAlert.tsx
  front-end/src/components/common/FileInput/FileInput.tsx
  front-end/src/components/common/Item/Item.tsx
  front-end/src/components/common/TabBar/ChatTabBar.tsx
  front-end/src/components/home/category/category.tsx
  front-end/src/components/layout/MobileLayout.tsx
  front-end/src/components/login/Join.tsx
  front-end/src/components/login/LoginButtons.tsx
  front-end/src/components/login/OAuthCallback.tsx
  front-end/src/components/new/itemEditor/ItemEditor.tsx
  front-end/src/components/new/itemEditor/TitleEditor.tsx
  front-end/src/components/region/RegionSelector.tsx
  front-end/src/components/region/SettingRegionMap.tsx
  front-end/src/components/region/SettingRegionSelector.tsx
  front-end/src/main.tsx
  front-end/src/pages/Home.tsx
  front-end/src/pages/ItemDetail.tsx
  front-end/src/pages/Login.tsx
  front-end/src/pages/SalesHistory.tsx
  front-end/src/pages/WishList.tsx
  front-end/src/routes/ProtectedRoute.tsx
Labels: feature, FE, refactor

#372 privateChatroom 구현
  iOS/second-hand/second-hand.xcodeproj/project.pbxproj
  iOS/second-hand/second-hand/Application/ButtonActionDelegate.swift
  iOS/second-hand/second-hand/Application/SocketActionDelegate.swift
  iOS/second-hand/second-hand/Application/Utils.swift
  iOS/second-hand/second-hand/Assets.xcassets/bubbleGray.imageset/Contents.json
  iOS/second-hand/second-hand/Assets.xcassets/bubbleGray.imageset/bubbleGray.png
  iOS/second-hand/second-hand/Assets.xcassets/bubbleOrange.imageset/Contents.json
  iOS/second-hand/second-hand/Assets.xcassets/bubbleOrange.imageset/bubbleOrange.png
  iOS/second-hand/second-hand/Chatting/subScene/PrivateChatroom/Controller/PrivateChatroomViewController.swift
  iOS/second-hand/second-hand/Chatting/subScene/PrivateChatroom/Model/PrivateChatroomChattingLogModel.swift
  iOS/second-hand/second-hand/Chatting/subScene/PrivateChatroom/View/BottomSectionInChatroom.swift
  iOS/second-hand/second-hand/Chatting/subScene/PrivateChatroom/View/Bubble.swift
  iOS/second-hand/second-hand/Chatting/subScene/PrivateChatroom/View/BubbleCell.swift
  iOS/second-hand/second-hand/Chatting/subScene/PrivateChatroom/View/MyBubble.swift
  iOS/second-hand/second-hand/Chatting/subScene/PrivateChatroom/View/MyCell.swift
  iOS/second-hand/second-hand/Chatting/subScene/PrivateChatroom/View/TableViewInChatroom.swift
  iOS/second-hand/second-hand/Chatting/subScene/PrivateChatroom/View/YourBubble.swift
  iOS/second-hand/second-hand/Chatting/subScene/PrivateChatroom/View/YourCell.swift
  iOS/second-hand/second-hand/MyAccount/SubScene/Join/Controller/JoinViewController.swift
  iOS/second-hand/second-hand/Network/CodableTemplate.swift
  iOS/second-hand/second-hand/Network/HTTPErrors.swift
  iOS/second-hand/second-hand/Network/NetworkManager.swift
  iOS/second-hand/second-hand/Network/Server.swift
  iOS/second-hand/second-hand/Network/SocketManager.swift
Labels: feature, iOS

#373 [#346] TODO 수정
  front-end/src/components/common/Alert/Alert.tsx
  front-end/src/components/common/Item/Item.tsx
  front-end/src/components/common/PopupSheet/PopupSheet.tsx
  front-end/src/components/common/PopupSheet/constants.ts
  front-end/src/components/home/ItemList/ItemList.tsx
  front-end/src/components/home/category/category.tsx
  front-end/src/components/layout/MobileLayout.tsx
  front-end/src/components/layout/PortalLayout.tsx
  front-end/src/components/login/Join.tsx
  front-end/src/components/login/LoginButtons.tsx
  front-end/src/components/login/OAuthCallback.tsx
  front-end/src/components/new/CategoryList.tsx
  front-end/src/components/new/New.tsx
  front-end/src/components/new/itemEditor/ItemEditor.tsx
  front-end/src/components/new/itemEditor/TitleEditor.tsx
  front-end/src/components/region/SearchRegions.tsx
  front-end/src/components/region/SettingRegionSelector.tsx
  front-end/src/pages/Home.tsx
  front-end/src/pages/ItemDetail.tsx
  front-end/src/pages/Login.tsx
  front-end/src/pages/SalesHistory.tsx
  front-end/src/pages/WishList.tsx
  front-end/src/utils/formatText.ts
  front-end/src/utils/getElapsedTime.ts
  front-end/src/utils/sessionStorage.ts
Labels: feature, FE

#381 refactor를 위한 todo 작성
  front-end/src/assets/Icon.tsx
  front-end/src/assets/category/baby.png
  front-end/src/assets/category/beauty.png
  front-end/src/assets/category/book.png
  front-end/src/assets/category/car.png
  front-end/src/assets/category/digital.png
  front-end/src/assets/category/domestic.png
  front-end/src/assets/category/etc.png
  front-end/src/assets/category/furniture.png
  front-end/src/assets/category/game.png
  front-end/src/assets/category/kitchen.png
  front-end/src/assets/category/man-apparel.png
  front-end/src/assets/category/pet.png
  front-end/src/assets/category/plant.png
  front-end/src/assets/category/processed-foods.png
  front-end/src/assets/category/sports.png
  front-end/src/assets/category/ticket.png
  front-end/src/assets/category/woman-accessories.png
  front-end/src/assets/category/woman-apparel.png
  front-end/src/components/chat/ChatRoom/ChatRoom.tsx
  front-end/src/components/chat/ChatRoomList/ChatListItem.tsx
  front-end/src/components/chat/ChatRoomList/ChatRoomList.tsx
  front-end/src/components/common/Alert/Alert.tsx
  front-end/src/components/common/Alert/constants.ts
  front-end/src/components/common/Button/Button.tsx
  front-end/src/components/common/FileInput/FileInput.tsx
  front-end/src/components/common/ImgBox/ImgBox.tsx
  front-end/src/components/common/Item/Item.tsx
  front-end/src/components/common/LabelInput/LabelInput.tsx
  front-end/src/components/common/PopupSheet/PopupSheet.tsx
  front-end/src/components/common/Spinner/index.ts
  front-end/src/components/common/TabBar/MainTabBar.tsx
  front-end/src/components/common/TabBar/TabBar.tsx
  front-end/src/components/common/Textarea/Textarea.tsx
  front-end/src/components/login/UserProfile.tsx
  front-end/src/components/new/index.ts
  front-end/src/components/new/itemEditor/ImageEditor.tsx
  front-end/src/components/new/itemEditor/ItemEditor.tsx
  front-end/src/components/new/itemEditor/index.ts
  front-end/src/pages/WishList.tsx
Labels: FE

#391 HOT FIX : 채팅방 목록 조회 에러 수정
  backend/src/main/java/com/team5/secondhand/api/chatroom/controller/ChatroomController.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/service/ChatroomFacade.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/response/MemberDetails.java
  backend/src/main/java/com/team5/secondhand/chat/chatroom/service/ChatroomCacheService.java
Labels: BE, debug

#392 [#390] HOTFIX: 중복 응답 헤더 제거
  backend/src/main/java/com/team5/secondhand/api/chatroom/controller/ChatroomController.java
  backend/src/main/java/com/team5/secondhand/chat/notification/service/NotificationService.java
Labels: BE, debug

#394 FIX: CI/CD 수정
  .github/workflows/aws.yml
  backend/src/main/java/com/team5/secondhand/global/aws/domain/Directory.java
  backend/src/main/java/com/team5/secondhand/global/config/WebConfig.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/schema.sql
  docker-compose.yml
Labels: BE

#396 HOT FIX: 기본키 생성 로직 추가
  backend/src/main/java/com/team5/secondhand/api/chatroom/domian/Chatroom.java
Labels: BE, debug

#397 FEAT: 채팅방에 접속해 있을 경우 메시지 알림 없음
  backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
  backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
  backend/src/main/java/com/team5/secondhand/chat/chatroom/domain/Chatroom.java
  backend/src/main/java/com/team5/secondhand/chat/chatroom/domain/Participants.java
  backend/src/main/java/com/team5/secondhand/chat/notification/dto/ChatNotification.java
  backend/src/main/java/com/team5/secondhand/chat/notification/service/NotificationService.java
  backend/src/main/java/com/team5/secondhand/chat/notification/service/SendChatNotificationUsecase.java
  backend/src/main/java/com/team5/secondhand/chat/session/service/SessionService.java
  backend/src/main/java/com/team5/secondhand/global/exception/GlobalExceptionHandler.java
  backend/src/main/resources/db/schema.sql
  nginx/conf.d/nginx.conf
Labels: BE, feature
