Repository masters2023-2nd-project-05/second-hand, pull requests merged in 2023-06, with the labels that each got.

#4 [iOS] 스위프트 프로젝트 초기 세팅
  iOS/.gitignore
  iOS/second-hand/Podfile
  iOS/second-hand/Podfile.lock
  iOS/second-hand/second-hand.xcodeproj/project.pbxproj
  iOS/second-hand/second-hand.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/second-hand/second-hand.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/second-hand/second-hand.xcodeproj/project.xcworkspace/xcuserdata/hwajin.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/second-hand/second-hand.xcodeproj/xcuserdata/hwajin.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/second-hand/second-hand/AppDelegate.swift
  iOS/second-hand/second-hand/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/second-hand/second-hand/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/second-hand/second-hand/Assets.xcassets/Contents.json
  iOS/second-hand/second-hand/Base.lproj/LaunchScreen.storyboard
  iOS/second-hand/second-hand/Base.lproj/Main.storyboard
  iOS/second-hand/second-hand/Info.plist
  iOS/second-hand/second-hand/SceneDelegate.swift
  iOS/second-hand/second-hand/ViewController.swift
Labels: iOS

#10 Be/007 build test
  .github/workflows/publish.yml
Labels: BE, feature

#19 프로젝트 초기 설정
  .github/workflows/publish.yml
  backend/.gitignore
  backend/Dockerfile
  backend/Dockerfile-nginx
  backend/build.gradle
  backend/docker-compose.yml
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/nginx/conf.d/nginx.conf
  backend/settings.gradle
  backend/src/main/java/com/team5/secondhand/BackendApplication.java
  backend/src/main/java/com/team5/secondhand/global/config/ApiDocsConfig.java
  backend/src/main/java/com/team5/secondhand/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/team5/secondhand/global/exception/dto/ErrorResponse.java
  backend/src/main/java/com/team5/secondhand/temp/controller/TestApiController.java
  backend/src/main/java/com/team5/secondhand/temp/dto/PostRequest.java
  backend/src/main/java/com/team5/secondhand/temp/dto/PostResponse.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/team5/secondhand/BackendApplicationTests.java
Labels: BE, feature

#20 [#1] FEAT: cours 임시 설정
  backend/src/main/java/com/team5/secondhand/global/config/WebConfig.java
Labels: BE, feature

#21 [#1] FIX: cours 시그니처 오타 수정
  backend/src/main/java/com/team5/secondhand/global/config/WebConfig.java
Labels: BE, feature

#25 [#24] FEAT: 로그인 페이지 로그인 기능 구현
  front-end/index.html
  front-end/package.json
  front-end/public/favicon.ico
  front-end/src/App.tsx
  front-end/src/assets/svgs/arrowUp.svg
  front-end/src/assets/svgs/camera.svg
  front-end/src/assets/svgs/chevronDown.svg
  front-end/src/assets/svgs/chevronLeft.svg
  front-end/src/assets/svgs/circleFill.svg
  front-end/src/assets/svgs/ellipsis.svg
  front-end/src/assets/svgs/hamburger.svg
  front-end/src/assets/svgs/heart.svg
  front-end/src/assets/svgs/home.svg
  front-end/src/assets/svgs/keyboard.svg
  front-end/src/assets/svgs/location.svg
  front-end/src/assets/svgs/message.svg
  front-end/src/assets/svgs/newspaper.svg
  front-end/src/assets/svgs/person.svg
  front-end/src/assets/svgs/plus.svg
  front-end/src/assets/svgs/search.svg
  front-end/src/assets/svgs/x.svg
  front-end/src/main.tsx
  front-end/src/pages/Login.tsx
  front-end/src/styles/globalStyles.ts
Labels: feature, FE

#32 [#1] FEAT: yml 초안
  backend/src/main/resources/application-db-local.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/schema.sql
Labels: BE, feature

#36 [#35] FEAT: Icon 컴포넌트 생성
  front-end/src/App.tsx
  front-end/src/assets/Icon.tsx
  front-end/src/assets/svgs/index.ts
  front-end/src/assets/svgs/svg.d.ts
Labels: feature, FE

#40 [#6] CHORE: 절대 경로 설정
  front-end/.eslintrc.json
  front-end/.prettierrc
  front-end/src/App.tsx
  front-end/tsconfig.json
  front-end/vite.config.ts
Labels: feature, FE

#48 [#42] 공통 버튼 컴포넌트 구현
  front-end/package.json
  front-end/src/components/common/Button/Button.tsx
  front-end/src/components/common/Button/index.ts
  front-end/src/styles/globalStyles.ts
Labels: feature, FE

#49 [#18] FEAT: Image Box 컴포넌트 생성
  front-end/.storybook/preview.ts
  front-end/src/components/common/ImgBox/ImgBox.tsx
  front-end/src/components/common/ImgBox/index.ts
Labels: feature, FE

#55 [#53] mobile layout
  front-end/src/App.tsx
  front-end/src/pages/Layout.tsx
  front-end/src/pages/Login.tsx
  front-end/src/routes/AppRouter.tsx
  front-end/src/styles/globalStyles.ts
Labels: feature, FE

#52 [#50] FEAT: Item 컴포넌트 UI 생성
  front-end/src/components/common/Item/Item.tsx
  front-end/src/components/common/Item/index.ts
  front-end/src/mock/mockData.ts
Labels: feature, FE

#39 [#37] FEAT: Chip 컴포넌트 생성
  front-end/src/components/common/Chip/Chip.tsx
  front-end/src/components/common/Chip/index.ts
Labels: feature, FE

#61 [#43] FEAT: PopupSheet 컴포넌트 생성
  front-end/src/components/common/PopupSheet/PopupSheet.tsx
  front-end/src/components/common/PopupSheet/index.ts
  front-end/src/constants/popupSheetMenu.ts
  front-end/src/pages/Layout.tsx
  front-end/tsconfig.json
  front-end/vite.config.ts
Labels: feature, FE

#62 [#45] nav bar 컴포넌트 생성
  front-end/src/components/common/NavBar/NavBar.tsx
  front-end/src/components/common/NavBar/index.ts
Labels: feature, FE

#69 [#34] S3 이미지 호스팅 service 구현
  backend/build.gradle
  backend/docker-compose.yml
  backend/src/main/java/com/team5/secondhand/global/aws/config/AwsConfiguration.java
  backend/src/main/java/com/team5/secondhand/global/aws/domain/Directory.java
  backend/src/main/java/com/team5/secondhand/global/aws/domain/Result.java
  backend/src/main/java/com/team5/secondhand/global/aws/dto/request/ItemImageUpload.java
  backend/src/main/java/com/team5/secondhand/global/aws/dto/request/ProfileImageUpload.java
  backend/src/main/java/com/team5/secondhand/global/aws/service/ImageHostService.java
  backend/src/main/java/com/team5/secondhand/global/dto/ErrorResponse.java
  backend/src/main/java/com/team5/secondhand/global/dto/GenericResponse.java
  backend/src/main/java/com/team5/secondhand/global/exception/EmptyBasedRegionException.java
  backend/src/main/java/com/team5/secondhand/global/exception/GlobalExceptionHandler.java
  backend/src/main/resources/application.yml
  etc/s3-java/src/main/java/example/Handler.java
  etc/s3-java/src/main/resources/log4j2.xml
Labels: BE, feature

#70 [#51] github oAuth 로 회원가입
  backend/build.gradle
  backend/src/main/java/com/team5/secondhand/global/dto/GenericResponse.java
  backend/src/main/java/com/team5/secondhand/global/oauth/config/OAuthProperties.java
  backend/src/main/java/com/team5/secondhand/global/oauth/controller/OAuthController.java
  backend/src/main/java/com/team5/secondhand/global/oauth/dto/OAuthToken.java
  backend/src/main/java/com/team5/secondhand/global/oauth/dto/UserProfile.java
  backend/src/main/java/com/team5/secondhand/global/oauth/service/OAuthService.java
  backend/src/main/resources/application.yml
Labels: BE, feature

#73 [#58] FEAT: textarea 구현
  front-end/src/components/common/Textarea/Textarea.tsx
  front-end/src/components/common/Textarea/index.ts
  front-end/src/hooks/useInput.tsx
  front-end/src/routes/AppRouter.tsx
Labels: feature, FE

#80 배포용 application yml 로 수정
  backend/src/main/java/com/team5/secondhand/api/member/domain/Member.java
  backend/src/main/java/com/team5/secondhand/api/member/domain/Oauth.java
  backend/src/main/resources/application.yml
Labels: BE, feature

#82 FEAT: 회원가입, 회원 프로필 이미지 수정
  backend/src/main/java/com/team5/secondhand/api/member/controller/MemberController.java
  backend/src/main/java/com/team5/secondhand/api/member/domain/BasedRegion.java
  backend/src/main/java/com/team5/secondhand/api/member/domain/Member.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/request/BasedRegionSummary.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/request/MemberJoin.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/response/MemberDetails.java
  backend/src/main/java/com/team5/secondhand/api/member/repository/MemberBasedRegionRepository.java
  backend/src/main/java/com/team5/secondhand/api/member/repository/MemberRepository.java
  backend/src/main/java/com/team5/secondhand/api/member/service/JoinService.java
  backend/src/main/java/com/team5/secondhand/api/member/service/MemberService.java
  backend/src/main/java/com/team5/secondhand/api/region/repository/RegionRepository.java
  backend/src/main/java/com/team5/secondhand/global/aws/dto/response/ProfileImageInfo.java
  backend/src/main/java/com/team5/secondhand/global/aws/exception/ImageHostingException.java
  backend/src/main/java/com/team5/secondhand/global/aws/exception/TooLargeImageException.java
  backend/src/main/java/com/team5/secondhand/global/aws/service/ImageHostService.java
  backend/src/main/java/com/team5/secondhand/global/aws/service/ProfileUploadUsecase.java
  backend/src/main/java/com/team5/secondhand/global/dto/ErrorResponse.java
  backend/src/main/java/com/team5/secondhand/global/exception/GlobalExceptionHandler.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/schema.sql
Labels: BE, feature

#83 Member 기능 테스트, Region controller, service, repository 초안 구현
  backend/src/main/java/com/team5/secondhand/api/region/controller/RegionController.java
  backend/src/main/java/com/team5/secondhand/api/region/exception/NotValidRegionException.java
  backend/src/main/java/com/team5/secondhand/api/region/service/RegionService.java
  backend/src/test/java/com/team5/secondhand/api/member/repository/MemberRepositoryTest.java
Labels: BE, feature

#85 [#81] git oAuth 로직 변경 수정
  backend/src/main/java/com/team5/secondhand/api/member/controller/MemberController.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/request/MemberLogin.java
  backend/src/main/java/com/team5/secondhand/api/member/exception/UnauthorizedException.java
  backend/src/main/java/com/team5/secondhand/api/member/service/MemberService.java
  backend/src/main/java/com/team5/secondhand/api/oauth/config/OAuthProperties.java
  backend/src/main/java/com/team5/secondhand/api/oauth/dto/OAuthToken.java
  backend/src/main/java/com/team5/secondhand/api/oauth/dto/UserProfile.java
  backend/src/main/java/com/team5/secondhand/api/oauth/service/OAuthService.java
  backend/src/main/java/com/team5/secondhand/global/dto/ErrorResponse.java
  backend/src/main/java/com/team5/secondhand/global/dto/ErrorResponseWithBody.java
  backend/src/main/java/com/team5/secondhand/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/team5/secondhand/global/oauth/controller/OAuthController.java
  backend/src/main/java/com/team5/secondhand/global/oauth/dto/UserProfile.java
Labels: BE, refactor

#86 [#81] FIX: 머지 충돌 오류 해결
  backend/src/main/java/com/team5/secondhand/api/member/controller/MemberController.java
Labels: BE

#87 [#81] 로그인 로직 구현
  backend/src/main/java/com/team5/secondhand/api/member/controller/MemberController.java
  backend/src/main/java/com/team5/secondhand/api/member/exception/UnauthorizedException.java
  backend/src/main/java/com/team5/secondhand/api/member/repository/MemberRepository.java
  backend/src/main/java/com/team5/secondhand/api/member/service/MemberService.java
  backend/src/main/resources/db/data.sql
  backend/src/test/java/com/team5/secondhand/api/member/repository/MemberRepositoryTest.java
Labels: BE, feature

#93 [#90] FEAT: item list 구현
  front-end/src/components/common/Item/Item.tsx
  front-end/src/components/common/Item/index.ts
  front-end/src/components/common/NavBar/NavBar.tsx
  front-end/src/components/common/TabBar/ChatTabBar.tsx
  front-end/src/components/common/TabBar/MainTabBar.tsx
  front-end/src/components/common/TabBar/SubTabBar.tsx
  front-end/src/components/common/TabBar/TabBar.tsx
  front-end/src/components/common/TabBar/index.ts
  front-end/src/components/common/Textarea/Textarea.tsx
  front-end/src/components/home/ItemList/ItemList.tsx
  front-end/src/components/home/ItemList/index.ts
  front-end/src/mock/mockData.ts
  front-end/src/pages/Home.tsx
  front-end/src/pages/Layout.tsx
  front-end/src/styles/globalStyles.ts
  front-end/src/util/formatNumberToSI.ts
Labels: feature, FE

#98 FIX: 프로필 사진 업로드 기능 에러 수정
  backend/src/main/java/com/team5/secondhand/api/member/controller/MemberController.java
  backend/src/main/java/com/team5/secondhand/api/member/domain/BasedRegion.java
  backend/src/main/java/com/team5/secondhand/api/member/service/MemberService.java
  backend/src/main/java/com/team5/secondhand/api/region/service/GetValidRegionsUsecase.java
  backend/src/main/java/com/team5/secondhand/api/region/service/RegionService.java
Labels: BE, feature

#102 [#101] FEAT: 아이템 목록 보기 v0.1
  backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/Item.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/ItemContents.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/ItemCounts.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/ItemDetailImage.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/Status.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/response/ItemList.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/response/ItemSummary.java
  backend/src/main/java/com/team5/secondhand/api/item/repository/ItemRepository.java
  backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
  backend/src/main/java/com/team5/secondhand/api/item/util/ImageUrlConverter.java
  backend/src/main/java/com/team5/secondhand/api/member/controller/MemberController.java
  backend/src/main/java/com/team5/secondhand/api/member/domain/BasedRegion.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/request/BasedRegionSummary.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/request/MemberJoin.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/request/MemberProfileImageUpdate.java
  backend/src/main/java/com/team5/secondhand/api/member/repository/MemberRepository.java
  backend/src/main/java/com/team5/secondhand/api/member/service/JoinService.java
  backend/src/main/java/com/team5/secondhand/api/member/service/MemberService.java
  backend/src/main/java/com/team5/secondhand/api/model/BaseTimeEntity.java
  backend/src/main/java/com/team5/secondhand/api/region/domain/Region.java
  backend/src/main/java/com/team5/secondhand/api/region/exception/NoMainRegionException.java
  backend/src/main/java/com/team5/secondhand/api/region/exception/NotValidRegionException.java
  backend/src/main/java/com/team5/secondhand/api/region/exception/RegionServiceException.java
  backend/src/main/java/com/team5/secondhand/api/region/repository/RegionRepository.java
  backend/src/main/java/com/team5/secondhand/api/region/service/GetValidRegionsUsecase.java
  backend/src/main/java/com/team5/secondhand/api/region/service/RegionService.java
  backend/src/main/java/com/team5/secondhand/global/aws/controller/ImageHostController.java
  backend/src/main/java/com/team5/secondhand/global/aws/service/ImageHostService.java
  backend/src/main/java/com/team5/secondhand/global/aws/service/ProfileUploadUsecase.java
  backend/src/main/java/com/team5/secondhand/global/exception/GlobalExceptionHandler.java
  backend/src/main/resources/db/schema.sql
Labels: BE, feature

#99 [#90] item list 마지막 아이템 border 제거
  front-end/src/components/home/ItemList/ItemList.tsx
  front-end/src/mock/mockData.ts
Labels: feature, FE

#105 [#53] Layout 반응형 value 수정
  front-end/src/components/common/NavBar/NavBar.tsx
  front-end/src/components/common/TabBar/MainTabBar.tsx
  front-end/src/components/common/TabBar/TabBar.tsx
  front-end/src/pages/Layout.tsx
Labels: FE, refactor

#107 [#90] Item 자동 fetch 기능 구현
  front-end/.gitignore
  front-end/package.json
  front-end/src/api.ts
  front-end/src/components/common/Button/Button.tsx
  front-end/src/components/common/ImgBox/ImgBox.tsx
  front-end/src/components/common/Item/Item.tsx
  front-end/src/components/common/Item/index.ts
  front-end/src/components/common/Spinner/Spinner.tsx
  front-end/src/components/home/ItemList/ItemList.tsx
  front-end/src/hooks/useIntersectionObserver.tsx
  front-end/src/mock/mockData.ts
  front-end/src/pages/Home.tsx
  front-end/src/pages/Layout.tsx
  front-end/src/utils/formatNumberToSI.ts
  front-end/tsconfig.json
  front-end/vite.config.ts
Labels: feature, FE

#109 #76 NetworkManager
  iOS/second-hand/second-hand.xcodeproj/project.pbxproj
  iOS/second-hand/second-hand/MyAccount/SubScene/Controller/GithubWebViewController.swift
  iOS/second-hand/second-hand/Network/GitUser+Region.swift
  iOS/second-hand/second-hand/Network/HTTPErrors.swift
  iOS/second-hand/second-hand/Network/HTTPMethod.swift
  iOS/second-hand/second-hand/Network/JSONCreater.swift
  iOS/second-hand/second-hand/Network/NetworkManager.swift
Labels: feature, iOS

#111 iOS 76 network manager
  iOS/second-hand/second-hand.xcodeproj/project.pbxproj
  iOS/second-hand/second-hand/MyAccount/SubScene/Controller/GithubWebViewController.swift
  iOS/second-hand/second-hand/Network/GitUser+Region.swift
  iOS/second-hand/second-hand/Network/HTTPErrors.swift
  iOS/second-hand/second-hand/Network/HTTPMethod.swift
  iOS/second-hand/second-hand/Network/JSONCreater.swift
  iOS/second-hand/second-hand/Network/NetworkManager.swift
Labels: feature, iOS

#113 [iOS] 위치설정 UI세팅
  iOS/second-hand/second-hand.xcodeproj/project.pbxproj
  iOS/second-hand/second-hand/CategoryButton.swift
  iOS/second-hand/second-hand/Home/ButtonCustomView.swift
  iOS/second-hand/second-hand/Home/Controller/HomeViewController.swift
  iOS/second-hand/second-hand/Home/SetLocationViewController.swift
  iOS/second-hand/second-hand/MyAccount/SubScene/Controller/JoinViewController.swift
Labels: feature, iOS

#119 [#101] TEST: 임의로 like가 들어갈 수 있도록 수정
  backend/src/main/java/com/team5/secondhand/api/item/domain/Item.java
  backend/src/main/java/com/team5/secondhand/api/item/repository/ItemRepository.java
  backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
Labels: BE, feature

#120 [#101] TEST: 임의로 like가 들어갈 수 있도록 수정
  backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
Labels: BE, feature

#121 [#81] 로그인 시 응답객체 수정 및 아이디 중복검사
  backend/src/main/java/com/team5/secondhand/api/member/controller/MemberController.java
  backend/src/main/java/com/team5/secondhand/api/member/domain/BasedRegion.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/request/BasedRegionSummary.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/response/MemberDetails.java
Labels: BE, feature

#124 [#81] member id로 db 조회 시 oauth 조건 추가
  backend/src/main/java/com/team5/secondhand/api/member/repository/MemberRepository.java
  backend/src/main/java/com/team5/secondhand/api/member/service/MemberService.java
Labels: BE, refactor

#125 FEAT: DTO에 enum 표시 형식 변경
  backend/src/main/java/com/team5/secondhand/api/item/domain/Status.java
  backend/src/main/java/com/team5/secondhand/api/member/domain/Oauth.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/request/MemberLogin.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/response/MemberDetails.java
Labels: BE, feature

#117 [#116] Blank 페이지 구현
  front-end/src/assets/svgs/carrot.svg
  front-end/src/assets/svgs/fullHeart.svg
  front-end/src/assets/svgs/index.ts
  front-end/src/pages/BlankPage.tsx
Labels: feature, FE

#127 FEAT: 회원가입 로직 수정
  backend/Dockerfile
  backend/build.gradle
  backend/docker-compose.yml
  backend/src/main/java/com/team5/secondhand/api/member/controller/MemberController.java
  backend/src/main/java/com/team5/secondhand/api/member/domain/Member.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/request/MemberJoin.java
  backend/src/main/java/com/team5/secondhand/api/member/exception/ExistMemberIdException.java
  backend/src/main/java/com/team5/secondhand/api/member/exception/MemberDataCorruptedException.java
  backend/src/main/java/com/team5/secondhand/api/member/exception/MemberException.java
  backend/src/main/java/com/team5/secondhand/api/member/exception/MemberExceptionHandler.java
  backend/src/main/java/com/team5/secondhand/api/member/exception/NotValidMemberIdException.java
  backend/src/main/java/com/team5/secondhand/api/member/exception/UnauthorizedException.java
  backend/src/main/java/com/team5/secondhand/api/member/exception/UnauthorizedGithubMemberException.java
  backend/src/main/java/com/team5/secondhand/api/member/service/JoinService.java
  backend/src/main/java/com/team5/secondhand/api/member/service/MemberService.java
  backend/src/main/java/com/team5/secondhand/api/oauth/dto/UserProfile.java
  backend/src/main/java/com/team5/secondhand/api/oauth/service/OAuthService.java
  backend/src/main/java/com/team5/secondhand/global/dto/ErrorResponseWithBody.java
  backend/src/main/java/com/team5/secondhand/global/exception/GlobalExceptionHandler.java
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
Labels: BE, feature

#131 [#081] jwt 관련 로직 완성
  backend/build.gradle
  backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
  backend/src/main/java/com/team5/secondhand/api/member/controller/MemberController.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/request/MemberLogin.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/response/MemberDetails.java
  backend/src/main/java/com/team5/secondhand/global/jwt/config/AuthenticationFilter.java
  backend/src/main/java/com/team5/secondhand/global/jwt/service/JwtService.java
  backend/src/main/java/com/team5/secondhand/global/jwt/util/JwtProperties.java
  backend/src/main/java/com/team5/secondhand/global/jwt/util/JwtUtils.java
  backend/src/main/java/com/team5/secondhand/temp/controller/TestApiController.java
  backend/src/main/java/com/team5/secondhand/temp/dto/PostRequest.java
  backend/src/main/java/com/team5/secondhand/temp/dto/PostResponse.java
  backend/src/main/resources/application.yml
Labels: BE, feature

#133 [#123] 2주차 리뷰 반영 리팩토링
  front-end/package.json
  front-end/src/assets/Icon.tsx
  front-end/src/assets/category/baby.png
  front-end/src/assets/category/beauty.png
  front-end/src/assets/category/book.png
  front-end/src/assets/category/car.png
  front-end/src/assets/category/digital.png
  front-end/src/assets/category/domestic.png
  front-end/src/assets/category/etc.png
  front-end/src/assets/category/furniture.png
  front-end/src/assets/category/game.png
  front-end/src/assets/category/kitchen.png
  front-end/src/assets/category/man-apparel.png
  front-end/src/assets/category/pet.png
  front-end/src/assets/category/plant.png
  front-end/src/assets/category/processed-foods.png
  front-end/src/assets/category/sports.png
  front-end/src/assets/category/ticket.png
  front-end/src/assets/category/woman-accessories.png
  front-end/src/assets/category/woman-apparel.png
  front-end/src/components/common/ImgBox/ImgBox.tsx
  front-end/src/components/common/Item/Item.tsx
  front-end/src/components/common/TabBar/MainTabBar.tsx
  front-end/src/components/common/Textarea/Textarea.tsx
Labels: FE, refactor

#136 [#135] 멤버 API 관련 서비스, 컨트롤러 예외처리
  backend/src/main/java/com/team5/secondhand/api/member/controller/MemberController.java
  backend/src/main/java/com/team5/secondhand/api/member/domain/Member.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/response/MemberDetails.java
  backend/src/main/java/com/team5/secondhand/api/member/exception/MemberExceptionHandler.java
  backend/src/main/java/com/team5/secondhand/api/member/service/MemberService.java
  backend/src/main/java/com/team5/secondhand/api/region/exception/EmptyBasedRegionException.java
  backend/src/main/java/com/team5/secondhand/api/region/exception/NoMainRegionException.java
  backend/src/main/java/com/team5/secondhand/api/region/exception/NotValidRegionException.java
  backend/src/main/java/com/team5/secondhand/api/region/exception/RegionException.java
  backend/src/main/java/com/team5/secondhand/api/region/exception/RegionExceptionHandler.java
  backend/src/main/java/com/team5/secondhand/api/region/exception/RegionServiceException.java
  backend/src/main/java/com/team5/secondhand/global/aws/controller/ImageHostController.java
  backend/src/main/java/com/team5/secondhand/global/aws/domain/Type.java
  backend/src/main/java/com/team5/secondhand/global/aws/exception/ImageHostException.java
  backend/src/main/java/com/team5/secondhand/global/aws/exception/ImageHostExceptionHandler.java
  backend/src/main/java/com/team5/secondhand/global/aws/exception/ImageHostingException.java
  backend/src/main/java/com/team5/secondhand/global/aws/exception/NotValidImageTypeException.java
  backend/src/main/java/com/team5/secondhand/global/aws/exception/TooLargeImageException.java
  backend/src/main/java/com/team5/secondhand/global/aws/service/ImageHostService.java
  backend/src/main/java/com/team5/secondhand/global/aws/service/ProfileUploadUsecase.java
  backend/src/main/java/com/team5/secondhand/global/exception/EmptyBasedRegionException.java
  backend/src/main/java/com/team5/secondhand/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/team5/secondhand/global/jwt/util/JwtUtils.java
Labels: BE, refactor

#138 FEAT: authority Interceptor
  backend/Dockerfile
  backend/src/main/java/com/team5/secondhand/api/member/controller/MemberController.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/request/MemberJoin.java
  backend/src/main/java/com/team5/secondhand/global/auth/interceptor/AuthorityInterceptor.java
  backend/src/main/java/com/team5/secondhand/global/config/WebConfig.java
  backend/src/main/java/com/team5/secondhand/global/exception/GlobalExceptionHandler.java
Labels: BE, feature

#139 Be/137 autherity interceptor
  backend/Dockerfile
  backend/src/main/java/com/team5/secondhand/global/auth/interceptor/AuthorityInterceptor.java
Labels: BE

#147 FEAT: 지역 검색 API 기능 v1.0
  backend/src/main/java/com/team5/secondhand/api/region/controller/RegionController.java
  backend/src/main/java/com/team5/secondhand/api/region/dto/RegionSummary.java
  backend/src/main/java/com/team5/secondhand/api/region/repository/RegionRepository.java
  backend/src/main/java/com/team5/secondhand/api/region/service/RegionService.java
  backend/src/main/resources/db/region_data.sql
  backend/src/main/resources/db/schema.sql
Labels: BE, feature

#148 FEAT: item page 반환시 이전/다음 페이지 여부와 함께 반환
  backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/response/ItemList.java
  backend/src/main/java/com/team5/secondhand/api/item/repository/ItemRepository.java
  backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
  backend/src/main/java/com/team5/secondhand/api/member/controller/MemberController.java
  backend/src/main/java/com/team5/secondhand/api/region/controller/RegionController.java
Labels: BE, feature

#143 관심목록 페이지 구현
  front-end/src/pages/WishList.tsx
  front-end/src/routes/router.tsx
  front-end/src/utils/getElapsedTime.ts
Labels: feature, FE

#158 [#141] 아이템 글 등록 및 수정 api 기본 구현
  backend/src/main/java/com/team5/secondhand/BackendApplication.java
  backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/Item.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/ItemContents.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/ItemCounts.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/ItemDetailImage.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/request/ItemImage.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/request/ItemPost.java
  backend/src/main/java/com/team5/secondhand/api/item/exception/ExistItemException.java
  backend/src/main/java/com/team5/secondhand/api/item/repository/ItemRepository.java
  backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
  backend/src/main/java/com/team5/secondhand/api/item/util/ImageUrlConverter.java
  backend/src/main/java/com/team5/secondhand/api/member/service/MemberService.java
  backend/src/main/java/com/team5/secondhand/api/region/service/GetValidRegionsUsecase.java
  backend/src/main/java/com/team5/secondhand/api/region/service/RegionService.java
Labels: BE, feature

#160 [#141] 머지 충돌 해결 및 버그 수정
  backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/Item.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/request/ItemPost.java
  backend/src/main/java/com/team5/secondhand/api/item/repository/ItemRepository.java
  backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
Labels: BE, feature

#162 [#161] 카테고리 전체 목록 출력
  backend/src/main/java/com/team5/secondhand/global/resource/controller/ResourceController.java
  backend/src/main/java/com/team5/secondhand/global/resource/domain/Category.java
  backend/src/main/java/com/team5/secondhand/global/resource/dto/response/CategoryDetail.java
  backend/src/main/java/com/team5/secondhand/global/resource/dto/response/CategoryList.java
  backend/src/main/java/com/team5/secondhand/global/resource/repository/CategoryRepository.java
  backend/src/main/java/com/team5/secondhand/global/resource/service/ResourceService.java
Labels: BE, feature

#165 사진 업로드 및 아이템 상세조회 구현
  backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/Item.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/ItemContents.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/ItemDetailImage.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/request/ItemImage.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/request/ItemPost.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/response/ItemDetail.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/response/Seller.java
  backend/src/main/java/com/team5/secondhand/api/item/exception/ItemExceptionHandler.java
  backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
  backend/src/main/java/com/team5/secondhand/api/member/controller/MemberController.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/request/MemberProfileImageUpdate.java
  backend/src/main/java/com/team5/secondhand/api/region/controller/RegionController.java
  backend/src/main/java/com/team5/secondhand/global/aws/controller/ImageHostController.java
  backend/src/main/java/com/team5/secondhand/global/aws/dto/request/ItemImageUpload.java
  backend/src/main/java/com/team5/secondhand/global/aws/dto/response/ImageInfo.java
  backend/src/main/java/com/team5/secondhand/global/aws/service/ImageHostService.java
  backend/src/main/java/com/team5/secondhand/global/aws/service/usecase/ItemDetailImageUpload.java
  backend/src/main/java/com/team5/secondhand/global/aws/service/usecase/ItemThumbnailImageUpload.java
  backend/src/main/java/com/team5/secondhand/global/aws/service/usecase/ProfileUpload.java
  backend/src/main/java/com/team5/secondhand/global/config/StringToOauth.java
  backend/src/main/resources/db/schema.sql
Labels: BE, feature

#142 [#134] 아이템 상세 페이지 구현
  front-end/src/assets/Icon.tsx
  front-end/src/assets/svgs/index.ts
  front-end/src/assets/svgs/selected.svg
  front-end/src/assets/svgs/unselected.svg
  front-end/src/components/common/NavBar/NavBar.tsx
  front-end/src/components/common/PopupSheet/PopupSheet.tsx
  front-end/src/components/common/PopupSheet/constants.ts
  front-end/src/components/common/TabBar/SubTabBar.tsx
  front-end/src/components/login/OAuthCallback.tsx
  front-end/src/pages/Home.tsx
  front-end/src/pages/ItemDetail.tsx
  front-end/src/pages/Layout.tsx
Labels: feature, FE

#166 [#90] REFACTOR: API 명세 변경에 의한 코드 수정
  front-end/src/components/common/Item/Item.tsx
  front-end/src/pages/Home.tsx
Labels: feature, FE

#154 112 로그인 페이지 구현
  front-end/src/components/common/FileInput/FileInput.tsx
  front-end/src/components/common/FileInput/index.ts
  front-end/src/components/common/NavBar/NavBar.tsx
  front-end/src/components/common/TabBar/TabBar.tsx
  front-end/src/components/login/IdInput.tsx
  front-end/src/components/login/Join.tsx
  front-end/src/components/login/LoginButtons.tsx
  front-end/src/components/login/OAuthCallback.tsx
  front-end/src/components/login/UserProfile.tsx
  front-end/src/pages/BlankPage.tsx
  front-end/src/pages/Home.tsx
  front-end/src/pages/Layout.tsx
  front-end/src/pages/Login.tsx
  front-end/src/pages/MyAccount.tsx
  front-end/src/routes/router.tsx
Labels: feature, FE

#170 [iOS] 데모데모
  iOS/second-hand/second-hand/MyAccount/SubScene/Join/Controller/JoinViewController.swift
Labels: iOS

#175 [iOS] 간단한 리팩토링
  iOS/second-hand/second-hand/CategoryButton.swift
  iOS/second-hand/second-hand/Home/ButtonCustomView.swift
  iOS/second-hand/second-hand/Home/HomeLeftBarButton.swift
  iOS/second-hand/second-hand/Home/HomeRightBarButton.swift
  iOS/second-hand/second-hand/Home/View/HomeProductCollectionViewCell.swift
  iOS/second-hand/second-hand/Home/subScene/RegisterNewProduct/RegisterNewProductViewController.swift
  iOS/second-hand/second-hand/Home/subScene/RegisterNewProduct/View/ProductImage.swift
  iOS/second-hand/second-hand/Home/subScene/RegisterNewProduct/View/RegisterProductScrollVeiw.swift
  iOS/second-hand/second-hand/Home/subScene/SetLocation/Controller/SetLocationViewController.swift
  iOS/second-hand/second-hand/MyAccount/Controller/NotLoginMyAccountViewController.swift
  iOS/second-hand/second-hand/MyAccount/SubScene/GithubWeb/Controller/GithubWebViewController.swift
  iOS/second-hand/second-hand/MyAccount/SubScene/Join/Controller/JoinViewController.swift
  iOS/second-hand/second-hand/MyAccount/View/IdStackView.swift
  iOS/second-hand/second-hand/TabBarControl/TabBarItem.swift
Labels: iOS

#186 Be/184 item post debug
  backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/Item.java
  backend/src/main/java/com/team5/secondhand/global/auth/interceptor/AuthorityInterceptor.java
Labels: BE

#187 [#184] FIX: Options cors 허용
  backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
  backend/src/main/java/com/team5/secondhand/global/config/WebConfig.java
Labels: BE, feature

#188 [#184] FIX: jwt 토큰 처리 방식 수정
  backend/src/main/java/com/team5/secondhand/api/member/controller/MemberController.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/response/MemberDetailsWithToken.java
  backend/src/main/java/com/team5/secondhand/global/jwt/service/JwtService.java
Labels: BE, feature

#189 FIX: basedRegion에 region id 버그 수정
  backend/src/main/java/com/team5/secondhand/api/member/dto/request/BasedRegionSummary.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/response/MemberDetails.java
  backend/src/main/java/com/team5/secondhand/global/config/WebConfig.java
Labels: BE, feature

#190 [#184] FIX: cors 설정 수정
  backend/src/main/java/com/team5/secondhand/global/config/WebConfig.java
Labels: BE, feature

#192 [#18] 이미지 박스 사이즈 고정을 위한 스타일 수정
  front-end/src/components/common/ImgBox/ImgBox.tsx
  front-end/src/pages/Home.tsx
Labels: feature, FE, refactor

#198 [#184] FIX: imagePost validation 수정
  backend/src/main/java/com/team5/secondhand/api/item/domain/Item.java
Labels: BE, feature

#199 Be/184 item post debug
  backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
  backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
  backend/src/main/java/com/team5/secondhand/api/region/service/RegionService.java
  backend/src/main/java/com/team5/secondhand/global/aws/exception/ImageHostExceptionHandler.java
  backend/src/main/java/com/team5/secondhand/global/aws/service/ImageHostService.java
Labels: BE, feature

#202 관심목록 API 완성
  backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/response/CategoryList.java
  backend/src/main/java/com/team5/secondhand/api/item/repository/ItemRepository.java
  backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
  backend/src/main/java/com/team5/secondhand/api/member/service/MemberService.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/controller/WishlistController.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/domain/Wishlist.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/dto/request/WishlistFilter.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/dto/request/WishlistItem.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/dto/response/CategoryList.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/dto/response/WishItem.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/dto/response/WishItemList.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/exception/ExistWishlistException.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/exception/WishlistExceptionHandler.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/repository/WishlistRepository.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/service/WishlistService.java
Labels: BE

#205 [#179] FIX: 목록 출력시 역방향으로 변경
  backend/src/main/java/com/team5/secondhand/api/wishlist/repository/WishlistRepository.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/service/WishlistService.java
Labels: BE

#204 Fe/159 new item
  front-end/src/assets/svgs/chevronRight.svg
  front-end/src/assets/svgs/index.ts
  front-end/src/components/common/LabelInput/LabelInput.tsx
  front-end/src/components/common/NavBar/NavBar.tsx
  front-end/src/components/common/PopupSheet/PopupSheet.tsx
  front-end/src/components/layout/MobileLayout.tsx
  front-end/src/components/layout/PortalLayout.tsx
  front-end/src/components/new/CategoryList.tsx
  front-end/src/components/new/New.tsx
  front-end/src/components/new/itemEditor/ImageEditor.tsx
  front-end/src/components/new/itemEditor/ItemEditor.tsx
  front-end/src/components/new/itemEditor/TitleEditor.tsx
  front-end/src/pages/Home.tsx
  front-end/src/routes/router.tsx
  front-end/src/styles/globalStyles.ts
  front-end/src/utils/convertFile.ts
  front-end/src/utils/formatText.ts
Labels: feature, FE

#209 add profile size
  front-end/src/components/login/UserProfile.tsx
Labels: feature, FE

#178 [#172] FEAT: useAPI 커스텀훅을 이용한 로직 변경
  front-end/src/api.ts
  front-end/src/components/common/Chip/Chip.tsx
  front-end/src/components/common/FileInput/FileInput.tsx
  front-end/src/components/login/IdInput.tsx
  front-end/src/components/login/Join.tsx
  front-end/src/components/login/LoginButtons.tsx
  front-end/src/components/login/OAuthCallback.tsx
  front-end/src/components/login/UserProfile.tsx
  front-end/src/hooks/useAPI.tsx
  front-end/src/hooks/useJoin.tsx
  front-end/src/pages/Login.tsx
  front-end/src/utils/getConvertedFile.ts
Labels: feature, FE

#215 [#197] FEAT: 웹소켓 테스트의 대여정
  backend/build.gradle
  backend/src/main/java/com/team5/secondhand/BackendApplication.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/request/ItemPost.java
  backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
  backend/src/main/java/com/team5/secondhand/chat/config/WebSocketConfig.java
  backend/src/main/java/com/team5/secondhand/chat/config/WebSocketHandler.java
  backend/src/main/java/com/team5/secondhand/chat/config/WebSocketMessageBroker.java
  backend/src/main/java/com/team5/secondhand/chat/controller/MessageBrokerController.java
  backend/src/main/java/com/team5/secondhand/chat/domain/ChatBubble.java
  backend/src/main/java/com/team5/secondhand/chat/domain/ChatRoom.java
  backend/src/main/java/com/team5/secondhand/chat/domain/MessageType.java
  backend/src/main/java/com/team5/secondhand/chat/repository/ChatRoomRepository.java
  backend/src/main/java/com/team5/secondhand/chat/repository/InMemoryChatRoomRepository.java
  backend/src/main/java/com/team5/secondhand/chat/service/ChatService.java
  backend/src/main/java/com/team5/secondhand/global/config/CacheConfig.java
  backend/src/main/java/com/team5/secondhand/global/config/RedisConfig.java
  backend/src/main/resources/application-db-local.yml
  backend/src/main/resources/db/schema.sql
Labels: BE, feature

#217 [iOS] 상품리스트 작업중인거 일단 머지
  iOS/second-hand/second-hand.xcodeproj/project.pbxproj
  iOS/second-hand/second-hand/Home/Controller/HomeViewController.swift
  iOS/second-hand/second-hand/Home/Model/SellingItem.swift
  iOS/second-hand/second-hand/Home/View/HomeProductCollectionViewCell.swift
  iOS/second-hand/second-hand/UIExtensions/UIStackView+extension.swift
Labels: feature, iOS

#218 API 버그 수정
  backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/response/ItemDetail.java
  backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/controller/WishlistController.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/dto/response/WishItemList.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/repository/WishlistRepository.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/service/WishlistService.java
Labels: BE, request

#220 API 버그 수정
  backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/response/ItemDetail.java
  backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/controller/WishlistController.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/dto/response/WishItemList.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/repository/WishlistRepository.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/service/WishlistService.java
Labels: BE

#221 [#63] FEAT: SegmentedControl 컴포넌트 구현
  front-end/src/components/common/SegmentedControl/SegmentedControl.tsx
  front-end/src/components/common/SegmentedControl/index.ts
  front-end/src/pages/SalesHistory.tsx
Labels: feature, FE

#223 3주차 리뷰반영
  backend/src/main/java/com/team5/secondhand/api/item/domain/ItemContents.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/ItemDetailImage.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/request/ItemImage.java
  backend/src/main/java/com/team5/secondhand/api/member/exception/MemberExceptionHandler.java
  backend/src/main/java/com/team5/secondhand/api/member/exception/UnauthorizedGithubMemberException.java
  backend/src/main/java/com/team5/secondhand/global/aws/service/ImageHostService.java
  backend/src/main/java/com/team5/secondhand/global/dto/ErrorResponseWithBody.java
Labels: BE

#208 [#191] chat list 구현
  front-end/src/components/chat/ChatList/ChatList.tsx
  front-end/src/components/chat/ChatList/ChatListItem.tsx
  front-end/src/components/chat/ChatList/index.ts
  front-end/src/components/chat/ChatRoom/ChatRoom.tsx
  front-end/src/components/common/Button/Button.tsx
  front-end/src/pages/ChatList.tsx
  front-end/src/pages/ChatRooms.tsx
  front-end/src/pages/Home.tsx
  front-end/src/routes/router.tsx
Labels: feature, FE

#225 [#213] FIX: 인터셉터 수정
  backend/docker-compose.yml
  backend/src/main/java/com/team5/secondhand/global/auth/interceptor/AuthorityInterceptor.java
  backend/src/main/java/com/team5/secondhand/global/config/WebConfig.java
  backend/src/main/resources/application-local.yml
Labels: BE, feature

#216 관심목록 페이지 구현
  front-end/src/components/common/LabelInput/LabelInput.tsx
  front-end/src/components/new/New.tsx
  front-end/src/components/new/itemEditor/ItemEditor.tsx
  front-end/src/pages/Home.tsx
  front-end/src/pages/WishList.tsx
Labels: feature, FE

#226 [#134] 홈 - 아이템 상세 연결
  front-end/src/components/common/Item/Item.tsx
  front-end/src/components/home/ItemList/ItemList.tsx
  front-end/src/pages/Home.tsx
  front-end/src/pages/ItemDetail.tsx
Labels: feature, FE

#227 [#108] 카테고리 필터링 기능 구현
  front-end/src/pages/Home.tsx
Labels: feature, FE

#229 [#228] FEAT: portal 닫은 후 홈 재렌더링 기능 구현
  front-end/src/pages/Home.tsx
Labels: feature, FE

#232 [#134] FEAT: 아이템 상태 변경 후 렌더링
  front-end/src/pages/ItemDetail.tsx
Labels: feature, FE

#234 Be/233 item hits
  backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/response/ItemDetail.java
  backend/src/main/java/com/team5/secondhand/api/item/repository/ItemRepository.java
  backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
  backend/src/main/java/com/team5/secondhand/api/region/service/RegionService.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/repository/WishlistRepository.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/service/CheckMemberLikedUsecase.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/service/WishlistService.java
Labels: BE, feature

#239 API 통신 패스 수정 및 아이템 상세 닫은 후 리프레쉬
  front-end/src/components/login/Join.tsx
  front-end/src/pages/Home.tsx
  front-end/src/pages/ItemDetail.tsx
Labels: feature, FE
