Repository masters2023-2nd-project-05/second-hand, pull requests merged in 2023-10, with the labels that each got.

#416 Update: 리팩토링
  backend/build.gradle
  backend/src/main/java/com/team5/secondhand/api/chatroom/domian/Chatroom.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/dto/response/ChatLog.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/dto/response/ChatroomList.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/dto/response/ChatroomSummary.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/repository/ChatroomRepository.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/service/ChatroomFacade.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/service/ChatroomService.java
  backend/src/main/java/com/team5/secondhand/api/item/controller/v1/ItemControllerV1.java
  backend/src/main/java/com/team5/secondhand/api/item/controller/v1/dto/request/ItemPost.java
  backend/src/main/java/com/team5/secondhand/api/item/controller/v1/dto/request/ItemUpdateRequest.java
  backend/src/main/java/com/team5/secondhand/api/item/controller/v1/dto/request/ItemsOffsetRequest.java
  backend/src/main/java/com/team5/secondhand/api/item/controller/v1/dto/request/MyItemsRequest.java
  backend/src/main/java/com/team5/secondhand/api/item/controller/v1/dto/request/RequestedItemImages.java
  backend/src/main/java/com/team5/secondhand/api/item/controller/v1/dto/response/ItemDetail.java
  backend/src/main/java/com/team5/secondhand/api/item/controller/v2/ItemControllerV2.java
  backend/src/main/java/com/team5/secondhand/api/item/controller/v2/ItemFacade.java
  backend/src/main/java/com/team5/secondhand/api/item/controller/v2/dto/ItemsCursorRequest.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/Item.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/ItemContents.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/ItemCounts.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/ItemDetailImage.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/ItemImage.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/Status.java
  backend/src/main/java/com/team5/secondhand/api/item/repository/ItemRepository.java
  backend/src/main/java/com/team5/secondhand/api/item/repository/ItemSliceRepository.java
  backend/src/main/java/com/team5/secondhand/api/item/repository/ItemSliceRepositoryImpl.java
  backend/src/main/java/com/team5/secondhand/api/item/service/ItemPostService.java
  backend/src/main/java/com/team5/secondhand/api/item/service/ItemReadService.java
  backend/src/main/java/com/team5/secondhand/api/item/service/dto/ItemListFilter.java
  backend/src/main/java/com/team5/secondhand/api/item/util/ImageUrlConverter.java
  backend/src/main/java/com/team5/secondhand/api/resource/controller/ResourceController.java
  backend/src/main/java/com/team5/secondhand/api/resource/domain/Category.java
  backend/src/main/java/com/team5/secondhand/api/resource/dto/response/CategoryDetail.java
  backend/src/main/java/com/team5/secondhand/api/resource/dto/response/CategoryList.java
  backend/src/main/java/com/team5/secondhand/api/resource/repository/CategoryRepository.java
  backend/src/main/java/com/team5/secondhand/api/resource/service/ResourceService.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/controller/ChatController.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/service/ChatBubbleService.java
  backend/src/main/java/com/team5/secondhand/chat/chatroom/config/ChatroomConfig.java
  backend/src/main/java/com/team5/secondhand/chat/chatroom/domain/Chatroom.java
  backend/src/main/java/com/team5/secondhand/chat/chatroom/service/ChatroomCacheService.java
  backend/src/main/java/com/team5/secondhand/global/aws/service/ImageHostService.java
  backend/src/main/java/com/team5/secondhand/global/aws/service/usecase/ItemDetailImageUpload.java
  backend/src/main/java/com/team5/secondhand/global/config/CacheConfig.java
  backend/src/main/java/com/team5/secondhand/global/config/QueryDslConfig.java
  backend/src/main/java/com/team5/secondhand/global/config/RedisConfig.java
  backend/src/main/resources/application-db-local.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/dummyData.sql
  backend/src/test/java/com/team5/secondhand/api/item/domain/ItemContentsTest.java
  backend/src/test/java/com/team5/secondhand/api/item/domain/ItemTest.java
  backend/src/test/java/com/team5/secondhand/api/item/domain/StatusTest.java
Labels: BE, feature

#419 FIX: 판매내역 에러 수정 및 채팅방 업데이트 시간 버그 수정
  backend/src/main/java/com/team5/secondhand/api/chatroom/dto/response/ChatroomSummary.java
  backend/src/main/java/com/team5/secondhand/api/item/controller/v1/dto/response/MyItemList.java
  backend/src/main/java/com/team5/secondhand/api/item/controller/v1/dto/response/MyItemSummary.java
  backend/src/main/java/com/team5/secondhand/api/item/repository/ItemSliceRepository.java
  backend/src/main/java/com/team5/secondhand/api/item/repository/ItemSliceRepositoryImpl.java
  backend/src/main/java/com/team5/secondhand/api/item/service/ItemReadService.java
Labels: BE, debug

#420 HOTFIX: 전반적인 오류 수정
  backend/src/main/java/com/team5/secondhand/api/chatroom/domian/Chatroom.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/service/ChatBubbleService.java
  backend/src/main/java/com/team5/secondhand/chat/chatroom/service/ChatroomCacheService.java
  backend/src/main/java/com/team5/secondhand/chat/topic/service/RedisMessagePublisher.java
  backend/src/main/resources/db/schema.sql
Labels: BE, debug

#422 반응형 웹 적용
  front-end/public/images/second-hand-background.png
  front-end/public/images/second-hand-icon.png
  front-end/src/App.tsx
  front-end/src/components/common/NavBar/NavBar.tsx
  front-end/src/components/common/PopupSheet/PopupSheet.tsx
  front-end/src/components/common/TabBar/TabBar.tsx
  front-end/src/components/home/category/category.tsx
  front-end/src/components/layout/DesktopLayout.tsx
  front-end/src/components/layout/Layout.tsx
  front-end/src/components/layout/PortalLayout.tsx
  front-end/src/components/layout/ResponsiveLayout.tsx
  front-end/src/components/login/Join.tsx
  front-end/src/components/new/itemEditor/ItemEditor.tsx
  front-end/src/components/region/SearchRegions.tsx
  front-end/src/components/region/SettingRegionMap.tsx
  front-end/src/hooks/useMediaQuery.tsx
  front-end/src/pages/Home.tsx
  front-end/src/pages/Login.tsx
  front-end/src/styles/globalStyles.ts
Labels: feature, FE

#423 usePortalBackDismiss, useCategory 작성
  front-end/src/components/layout/Layout.tsx
  front-end/src/components/layout/index.ts
  front-end/src/hooks/useBackDismiss.tsx
  front-end/src/hooks/useCategory.tsx
  front-end/src/hooks/usePortalBackDismiss.tsx
  front-end/src/pages/Home.tsx
  front-end/src/pages/ItemDetail.tsx
  front-end/src/pages/SalesHistory.tsx
  front-end/src/pages/WishList.tsx
  front-end/src/routes/router.tsx
Labels: feature, FE, refactor

#406 채팅방 입장 분기 처리 및 전반적인 코드 수정
  front-end/src/components/chat/ChatList/ChatList.tsx
  front-end/src/components/chat/ChatList/ChatListItem.tsx
  front-end/src/components/chat/ChatList/index.ts
  front-end/src/components/chat/ChatRoom/ChatBubbles.tsx
  front-end/src/components/chat/ChatRoom/ChatRoom.tsx
  front-end/src/components/chat/ChatRoomList/ChatRoomList.tsx
  front-end/src/components/chat/ChatRoomList/index.ts
  front-end/src/components/common/TabBar/ChatTabBar.tsx
  front-end/src/components/home/ItemDetail/Carousel.tsx
  front-end/src/pages/ChatPage.tsx
  front-end/src/pages/ItemDetail.tsx
  front-end/src/pages/WishList.tsx
Labels: feature, FE, refactor

#433 HOTFIX: 삭제된 채팅방 리스트 보임 오류 수정
  backend/src/main/java/com/team5/secondhand/api/chatroom/domian/Chatroom.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/service/ChatroomService.java
  backend/src/main/java/com/team5/secondhand/chat/chatroom/handler/StompMessageProcessor.java
  backend/src/main/java/com/team5/secondhand/chat/chatroom/service/ChatroomCacheService.java
Labels: BE
