Repository masters2023-2nd-project-05/second-hand, pull requests merged in 2023-12, with the labels that each got.

#476 FIX: SSE debug log 추가 및 삭제 로직 추가
  backend/src/main/java/com/team5/secondhand/chat/notification/repository/InmemoryNotificationRepository.java
  backend/src/main/java/com/team5/secondhand/chat/notification/repository/NotificationRepository.java
  backend/src/main/java/com/team5/secondhand/chat/notification/service/NotificationService.java
Labels: BE, debug

#477 FIX: 채팅 메시지 조회 쿼리 수정
  backend/src/main/java/com/team5/secondhand/chat/bubble/service/ChatBubbleService.java
Labels: BE, debug

#484 새로운 채팅 발생시 수신자에게 SSE 알람 발송 기능 구현
  backend/src/main/java/com/team5/secondhand/application/chatroom/dto/ChatroomInfo.java
  backend/src/main/java/com/team5/secondhand/application/chatroom/dto/response/ChatroomDetails.java
  backend/src/main/java/com/team5/secondhand/application/chatroom/service/ChatroomFacade.java
  backend/src/main/java/com/team5/secondhand/chat/notification/service/NotificationEventListener.java
  backend/src/main/java/com/team5/secondhand/chat/notification/service/NotificationService.java
  backend/src/main/java/com/team5/secondhand/chat/notification/service/SendChatNotificationUsecase.java
Labels: BE, feature

#485 [#475] FIX: 로직 오류 수정
  backend/src/main/java/com/team5/secondhand/application/chatroom/dto/response/ChatroomDetails.java
  backend/src/main/java/com/team5/secondhand/chat/notification/service/NotificationEventListener.java
Labels: BE

#482 Chat 관련 api 분리 및 리팩토링
  front-end/src/api/chat.ts
  front-end/src/api/index.ts
  front-end/src/components/chat/ChatRoom/ChatInput.tsx
  front-end/src/components/chat/ChatRoom/ChatRoom.tsx
  front-end/src/components/common/PopupSheet/constants.ts
  front-end/src/components/common/TabBar/ChatTabBar.tsx
  front-end/src/components/common/Textarea/Textarea.tsx
  front-end/src/components/home/category/index.ts
  front-end/src/components/layout/Layout.tsx
  front-end/src/components/new/New.tsx
  front-end/src/hooks/useCategory.tsx
  front-end/src/hooks/usePopupSheet.tsx
  front-end/src/pages/ChatPage.tsx
  front-end/src/pages/Home.tsx
  front-end/src/pages/ItemDetail.tsx
  front-end/src/pages/NotFound.tsx
  front-end/src/pages/WishList.tsx
  front-end/src/routes/router.tsx
Labels: feature, FE, refactor
