Repository masters2023-2nd-project-05/second-hand, pull requests merged in 2023-07, with the labels that each got.

#242 [iOS] 무한스크롤
  iOS/second-hand/second-hand/Home/Controller/HomeViewController.swift
Labels: feature, iOS

#245 FEAT: BE CORS 설정 수정
  backend/src/main/java/com/team5/secondhand/global/config/WebConfig.java
Labels: BE, feature

#250 채팅 테스트
  backend/src/main/java/com/team5/secondhand/chat/config/WebSocketConfig.java
  backend/src/main/java/com/team5/secondhand/chat/config/WebSocketHandler.java
  backend/src/main/java/com/team5/secondhand/chat/controller/ChatController.java
  backend/src/main/java/com/team5/secondhand/chat/controller/MessageBrokerController.java
  backend/src/main/java/com/team5/secondhand/chat/service/RedisMessagePublisher.java
  backend/src/main/java/com/team5/secondhand/chat/service/RedisMessageSubscriber.java
  backend/src/main/java/com/team5/secondhand/global/config/RedisConfig.java
Labels: BE, feature

#252 stomp 테스트 사이트 cors origin 허용
  backend/src/main/java/com/team5/secondhand/global/config/WebConfig.java
Labels: BE

#251 좋아요 목록 조회 시 삭제된 아이템 제외하고 조회하도록 수정
  backend/src/main/java/com/team5/secondhand/api/wishlist/repository/WishlistRepository.java
Labels: BE

#253 FIX: 로그인 안한상태에서 Item API 일부 허용
  backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
  backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/response/MemberDetails.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/service/CheckMemberLikedUsecase.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/service/WishlistService.java
  backend/src/main/java/com/team5/secondhand/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/team5/secondhand/global/jwt/config/AuthenticationFilter.java
  backend/src/main/resources/application-local.yml
Labels: BE, debug

#261 FEAT: chatroom 정보를 받을 수 있다.
  .github/workflows/deploy.yml
  backend/src/main/java/com/team5/secondhand/api/chatroom/controller/ChatRoomController.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/domian/ChatRoom.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/dto/response/ChatItem.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/dto/response/ChatItemDetails.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/dto/response/ChatroomDetails.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/exception/ChatRoomExceptionHandler.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/exception/ExistChatRoomException.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/repository/ChatRoomRepository.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/service/ChatRoomFacade.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/service/ChatRoomService.java
  backend/src/main/java/com/team5/secondhand/chat/repository/ChatRoomRepository.java
  backend/src/main/java/com/team5/secondhand/global/auth/interceptor/AuthorityInterceptor.java
  backend/src/main/java/com/team5/secondhand/global/config/WebConfig.java
  backend/src/main/resources/db/schema.sql
  backend/src/test/java/com/team5/secondhand/api/chatroom/domian/ChatRoomTest.java
  nginx/conf.d/nginx.conf
Labels: BE, feature

#265 [iOS] 아이템 상세페이지 API연동 /기능 / UI 구현
  iOS/second-hand/second-hand.xcodeproj/project.pbxproj
  iOS/second-hand/second-hand/Application/Utils.swift
  iOS/second-hand/second-hand/Home/Controller/HomeViewController.swift
  iOS/second-hand/second-hand/Home/subScene/ItemDetail/Controller/ItemDetailViewController.swift
  iOS/second-hand/second-hand/Home/subScene/ItemDetail/Model/ItemDetailModel.swift
  iOS/second-hand/second-hand/Home/subScene/ItemDetail/VIew/ContentOfPost.swift
  iOS/second-hand/second-hand/Home/subScene/ItemDetail/VIew/ItemDetailBottomSectionView.swift
  iOS/second-hand/second-hand/Home/subScene/ItemDetail/VIew/ItemDetailImageSectionView.swift
  iOS/second-hand/second-hand/Home/subScene/ItemDetail/VIew/ItemDetailTextSectionView.swift
  iOS/second-hand/second-hand/Home/subScene/ItemDetail/VIew/SellerInfoView.swift
  iOS/second-hand/second-hand/Home/subScene/ItemDetail/VIew/StatusButton.swift
  iOS/second-hand/second-hand/Network/CodableTemplate.swift
  iOS/second-hand/second-hand/Network/Server.swift
  iOS/second-hand/second-hand/UIExtensions/Int,String+Extension.swift
Labels: feature, iOS

#263 [#134] REFACTOR: count 관련 mapped 코드 수정
  front-end/src/pages/ItemDetail.tsx
Labels: FE, refactor

#264 [#230] chat room UI 및 WS 통신 로직
  front-end/package.json
  front-end/src/api.ts
  front-end/src/components/chat/ChatRoom/ChatRoom.tsx
  front-end/src/components/chat/ChatRoom/index.ts
  front-end/src/components/chat/ChatRoomList/ChatListItem.tsx
  front-end/src/components/chat/ChatRoomList/ChatRoomList.tsx
  front-end/src/components/common/ImgBox/ImgBox.tsx
  front-end/src/components/common/TabBar/ChatTabBar.tsx
  front-end/src/components/common/Textarea/Textarea.tsx
  front-end/src/pages/ChatPage.tsx
  front-end/src/pages/Home.tsx
Labels: feature, FE

#274 [#273] FIX: 쿼리 타입 오류 수정
  backend/src/main/java/com/team5/secondhand/api/wishlist/repository/WishlistRepository.java
Labels: BE, feature

#279 FIX: chatroom API 구현에 대한 debugging
  backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
  backend/src/main/java/com/team5/secondhand/api/item/repository/ItemSliceRepositoryImpl.java
  backend/src/main/java/com/team5/secondhand/api/region/service/RegionService.java
  backend/src/main/java/com/team5/secondhand/global/config/WebConfig.java
  backend/src/main/resources/db/schema.sql
Labels: BE, debug

#283 [#243] ADD: 아이템 등록시 헤더에 로그인 토큰을 추가
  iOS/second-hand/second-hand/Home/subScene/RegisterNewProduct/Controller/RegisterNewProductViewController.swift
  iOS/second-hand/second-hand/Network/JSONCreater.swift
Labels: iOS

#282 FEAT: 채팅 메시지 저장 기능
  backend/src/main/java/com/team5/secondhand/BackendApplication.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/controller/ChatroomController.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/domian/Chatroom.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/Item.java
  backend/src/main/java/com/team5/secondhand/api/wishlist/controller/WishlistController.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/config/WebSocketMessageBroker.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/controller/ChatController.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/controller/ChatLogController.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/domain/ChatBubble.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/domain/MessageType.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/dto/BubbleSummary.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/dto/ChatroomLog.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/repository/ChatBubbleRepository.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/service/ChatLogService.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/service/RedisMessagePublisher.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/service/RedisMessageSubscriber.java
  backend/src/main/java/com/team5/secondhand/chat/domain/ChatBubble.java
  backend/src/main/java/com/team5/secondhand/chat/domain/ChatRoom.java
  backend/src/main/java/com/team5/secondhand/chat/domain/MessageType.java
  backend/src/main/java/com/team5/secondhand/chat/repository/ChatRoomRepository.java
  backend/src/main/java/com/team5/secondhand/chat/repository/InMemoryChatRoomRepository.java
  backend/src/main/java/com/team5/secondhand/chat/service/ChatService.java
  backend/src/main/java/com/team5/secondhand/global/aws/service/ImageHostService.java
  backend/src/main/java/com/team5/secondhand/global/config/RedisConfig.java
  backend/src/main/java/com/team5/secondhand/global/config/WebConfig.java
  backend/src/main/java/com/team5/secondhand/global/model/BasedTimeEntity.java
  backend/src/main/java/com/team5/secondhand/global/model/UpdatedTimeEntity.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/team5/secondhand/api/chatroom/domian/ChatRoomTest.java
Labels: BE, feature

#290 [#289] FEAT: DTO 수정
  backend/src/main/java/com/team5/secondhand/api/member/dto/request/BasedRegionSummary.java
Labels: BE, feature

#293 [#275] 판매내역, 관심목록 필터기능
  front-end/src/components/common/TabBar/MainTabBar.tsx
  front-end/src/components/layout/MobileLayout.tsx
  front-end/src/hooks/useAPI.tsx
  front-end/src/pages/Home.tsx
  front-end/src/pages/SalesHistory.tsx
  front-end/src/pages/WishList.tsx
Labels: feature, FE

#294 채팅방 생성 버그 수정 및 채팅방 리스트 조회 API
  backend/src/main/java/com/team5/secondhand/api/chatroom/controller/ChatroomController.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/domian/Chatroom.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/dto/request/ChatItem.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/dto/response/ChatItem.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/dto/response/ChatItemSummary.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/dto/response/ChatMember.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/dto/response/ChatroomDetails.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/dto/response/ChatroomList.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/dto/response/ChatroomSummary.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/repository/ChatroomRepository.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/service/ChatroomFacade.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/service/ChatroomService.java
Labels: BE, feature

#296 채팅방 생성 및 리스트 조회 시 버그 수정
  backend/src/main/java/com/team5/secondhand/api/chatroom/controller/ChatroomController.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/dto/request/ChatItem.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/dto/response/ChatroomList.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/exception/BuyerException.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/exception/ChatRoomExceptionHandler.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/repository/ChatroomRepository.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/service/ChatroomFacade.java
  backend/src/main/java/com/team5/secondhand/api/chatroom/service/ChatroomService.java
  backend/src/main/java/com/team5/secondhand/api/item/domain/Item.java
Labels: BE, feature, refactor

#295 FEAT: 판매내역 API 수정
  backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/request/MyItemFilteredSlice.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/response/MyItemList.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/response/MyItemSummary.java
  backend/src/main/java/com/team5/secondhand/api/item/repository/ItemRepository.java
  backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
Labels: BE, feature

#297 FEAT: 이전 API 개선 사항 테스트 배포
  backend/src/main/java/com/team5/secondhand/api/item/controller/ItemController.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/request/MyItemFilteredSlice.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/response/MyItemList.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/response/MyItemSummary.java
  backend/src/main/java/com/team5/secondhand/api/item/repository/ItemRepository.java
  backend/src/main/java/com/team5/secondhand/api/item/service/ItemService.java
  backend/src/main/java/com/team5/secondhand/api/member/dto/request/BasedRegionSummary.java
Labels: BE, feature

#300 REFACTIR: Be/280 debugging chatbubble
  backend/src/main/java/com/team5/secondhand/chat/bubble/controller/ChatLogController.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/domain/ChatBubble.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/dto/response/BubbleSummary.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/dto/response/ChatroomLog.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/service/ChatLogService.java
Labels: BE, feature

#301 [#280] FIX: domain 수정
  backend/src/main/java/com/team5/secondhand/chat/bubble/domain/ChatBubble.java
Labels: BE, debug

#304 [#280] FIX: field 1개인 DTO 생성자 변경
  backend/src/main/java/com/team5/secondhand/api/item/dto/request/ItemImage.java
  backend/src/main/java/com/team5/secondhand/api/item/dto/request/ItemStatusUpdate.java
Labels: BE, debug

#303 [iOS] 위시리스트 관련 머지
  iOS/second-hand/second-hand.xcodeproj/project.pbxproj
  iOS/second-hand/second-hand/Application/AppDelegate.swift
  iOS/second-hand/second-hand/CategoryButton.swift
  iOS/second-hand/second-hand/Home/Controller/HomeViewController.swift
  iOS/second-hand/second-hand/Home/Model/SellingItem.swift
  iOS/second-hand/second-hand/Home/View/ProductListCollectionViewCell.swift
  iOS/second-hand/second-hand/Home/subScene/ItemDetail/Controller/ItemDetailViewController.swift
  iOS/second-hand/second-hand/Home/subScene/ItemDetail/VIew/ContentOfPost.swift
  iOS/second-hand/second-hand/Home/subScene/ItemDetail/VIew/ItemDetailBottomSectionView.swift
  iOS/second-hand/second-hand/MyAccount/Controller/NotLoginMyAccountViewController.swift
  iOS/second-hand/second-hand/MyAccount/SubScene/Join/Controller/JoinViewController.swift
  iOS/second-hand/second-hand/Network/CodableTemplate.swift
  iOS/second-hand/second-hand/Network/NetworkManager.swift
  iOS/second-hand/second-hand/Network/Server.swift
  iOS/second-hand/second-hand/WishListViewController.swift
Labels: feature, iOS

#307 [#280] TEST: 채팅 테스트를 위한 포트 cors 설정 변경
  backend/src/main/java/com/team5/secondhand/global/config/WebConfig.java
Labels: BE, feature

#306 [#305] 상품 수정 기능 구현
  front-end/src/components/new/New.tsx
  front-end/src/components/new/itemEditor/ImageEditor.tsx
  front-end/src/components/new/itemEditor/ItemEditor.tsx
  front-end/src/pages/ItemDetail.tsx
  front-end/src/utils/formatText.ts
Labels: feature, FE

#310 싱크맞추기용 MERGE
  iOS/second-hand/second-hand.xcodeproj/project.pbxproj
  iOS/second-hand/second-hand/Chatting/subScene/PrivateChatroom/Controller/PrivateChatroomViewController.swift
  iOS/second-hand/second-hand/Chatting/subScene/PrivateChatroom/Model/PrivateChatroomModel.swift
  iOS/second-hand/second-hand/Chatting/subScene/PrivateChatroom/View/ItemSummaryInChatroom.swift
  iOS/second-hand/second-hand/Home/subScene/ItemDetail/Controller/ItemDetailViewController.swift
  iOS/second-hand/second-hand/Network/ImageCacheManager.swift
  iOS/second-hand/second-hand/Network/JSONCreater.swift
  iOS/second-hand/second-hand/Network/SocketManager.swift
Labels: feature, iOS

#311 FEAT: 채팅 DB 저장 구조 변경
  backend/src/main/java/com/team5/secondhand/chat/bubble/domain/ChatBubble.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/dto/response/BubbleSummary.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/service/ChatLogService.java
  backend/src/main/java/com/team5/secondhand/chat/bubble/service/RedisMessagePublisher.java
  backend/src/main/java/com/team5/secondhand/global/config/RedisConfig.java
  backend/src/main/resources/application.yml
Labels: BE, feature

#314 [#308] REFACTOR: DTO 필드명 변경
  backend/src/main/java/com/team5/secondhand/chat/bubble/dto/response/BubbleSummary.java
Labels: BE, refactor

#320 Refactor: 사용하지 않는 코드 삭제
  backend/src/main/java/com/team5/secondhand/api/item/dto/request/ItemImage.java
  backend/src/main/java/com/team5/secondhand/api/member/service/MemberService.java
  backend/src/main/java/com/team5/secondhand/api/region/service/RegionService.java
  backend/src/main/java/com/team5/secondhand/global/jwt/config/AuthenticationFilter.java
Labels: BE, refactor

#309 [#134] FEAT: 상품 상세 이미지 슬라이드 기능 구현
  front-end/package.json
  front-end/src/components/home/ItemDetail/Carousel.tsx
  front-end/src/components/layout/PortalLayout.tsx
  front-end/src/pages/ItemDetail.tsx
Labels: feature, FE

#302 [#298] FEAT: Alert UI 컴포넌트 생성
  front-end/src/components/common/Alert/Alert.tsx
  front-end/src/components/common/Alert/constants.ts
  front-end/src/components/common/Alert/index.ts
  front-end/src/components/common/Alert/useAlert.tsx
  front-end/src/components/layout/PortalLayout.tsx
  front-end/src/pages/ItemDetail.tsx
Labels: feature, FE

#326 FEAT: 급하게 테스트 용 stomp 동작 시 로그 출력
  backend/src/main/java/com/team5/secondhand/chat/bubble/config/WebSocketMessageBroker.java
Labels: BE

#328 로그에 sessionId 정보 추가
  backend/src/main/java/com/team5/secondhand/chat/bubble/config/WebSocketMessageBroker.java
Labels: BE

#286 [#222] setting regions
  front-end/package.json
  front-end/src/assets/Icon.tsx
  front-end/src/components/common/Alert/Alert.tsx
  front-end/src/components/common/NavBar/NavBar.tsx
  front-end/src/components/common/PopupSheet/PopupSheet.tsx
  front-end/src/components/common/PopupSheet/constants.ts
  front-end/src/components/layout/PortalLayout.tsx
  front-end/src/components/login/Join.tsx
  front-end/src/components/new/CategoryList.tsx
  front-end/src/components/new/New.tsx
  front-end/src/components/new/itemEditor/ItemEditor.tsx
  front-end/src/components/new/itemEditor/TitleEditor.tsx
  front-end/src/components/region/RegionSelector.tsx
  front-end/src/components/region/SearchRegions.tsx
  front-end/src/components/region/SettingRegionMap.tsx
  front-end/src/components/region/SettingRegionSelector.tsx
  front-end/src/hooks/useGeoLocation.tsx
  front-end/src/pages/Home.tsx
  front-end/src/pages/ItemDetail.tsx
  front-end/src/utils/debounce.ts
Labels: feature, FE

#332 [#331] CHORE: ENV변수 설정
  front-end/.env.production
  front-end/src/components/login/OAuthCallback.tsx
Labels: FE, chore

#334 [#324] add alert
  front-end/src/components/common/Alert/Alert.tsx
  front-end/src/components/login/Join.tsx
  front-end/src/components/new/itemEditor/ItemEditor.tsx
  front-end/src/components/region/RegionSelector.tsx
  front-end/src/components/region/SettingRegionSelector.tsx
  front-end/src/pages/Home.tsx
  front-end/src/pages/Login.tsx
Labels: feature, FE
